### ISSUE TITLE
IP检测全红，但是节点又可以用

### ISSUE THREAD

**Issue by szsunny** [garypang13/openwrt-bypass#37]
> 
![11](https://user-images.githubusercontent.com/73342603/121295223-41cd2800-c921-11eb-9569-1c0e15c08f2f.png)

**Comment by touchsola** [comment]
节点全红+1，或者偶尔有几个是0ms，最近开始的，感觉和luasocket有关

**Comment by njf1993** [comment]
节点全红+1,但节点全能用，求大佬修复

**Comment by zwillhill** [comment]
今天编译的k3版，这个问题仍然存在。
