### ISSUE TITLE
不支持vless配置导入导出

### ISSUE THREAD

**Issue by zwillhill** [garypang13/openwrt-bypass#45]
提示不支持。目前只能手动填写vless节点内容，虽然使用上没区别，但最近经常得换节点。。

**Comment by garypang13** [comment]
已支持.

**Comment by zwillhill** [comment]
谢谢。经测试已经可用了，但是不能区分tls和xtls，只能导入tls）
helloworld的tls和xtls是并存选项所以不影响识别（即使链接里是xtls也会选中tls），bypass是单选
xtls格式链接格式如下
`vless://vlessid@域名:端口?security=xtls&flow=xtls-rprx-direct#XTLS_wulabing-域名`

**Comment by garypang13** [comment]
已修复.

**Comment by zwillhill** [comment]
流控识别错误，上面的链接flow=xtls-rprx-direct，应为xtls-rprx-direct，导入后识别为xtls-rprx-splice

**Comment by garypang13** [comment]
@zwillhill 已修复

**Comment by zwillhill** [comment]
@garypang13 经测试还是识别为splice。

**Comment by garypang13** [comment]
显示为splice保存后就变成direct了

**Comment by garypang13** [comment]
我测试了passwall也是这样的,默认总是显示为 direct 但是保存后 就会显示正常的信息,

**Comment by zwillhill** [comment]
> 我测试了passwall也是这样的,默认总是显示为 direct 但是保存后 就会显示正常的信息,

试了下的确是保存了就正确了。测试方法不够严谨。
